### ISSUE TITLE
Unable to create an environment

### ISSUE THREAD

**Issue by Corys9** [EchoAPI-Team/echoapi-for-vscode-support#17]
VSCode 1.97.2

I am unable to create an environment.

Steps:
1. Open "Global Para Settings" page.
2. Click "New Environment" button at the bottom.
3. (optional) Fill out anything.
4. There is no 'Save' button.

Closing the "Global Para Settings" page will cause the "New Environment" you created to disappear.
The dropdown for selecting an environment doesn't see it either way.

I tried resetting the zoom level for VSCode, hoping the 'Save' button was outside the screen, but no luck - it's just not there, nor is the environment automatically saved.
I tried restarting VSCode, no luck.

Am I doing something wrong?
I am not logged in to EchoAPI (you do advertise that no login is required).

**Comment by lara-joyet** [comment]
Hi there,

Thank you for reaching out! We're pleased to confirm this issue has been resolved in ​version 1.7.3​ ✅

Verification Steps:​
1️⃣ ​Environment Setup​
Navigate to the Environment section and populate all required fields.
2️⃣ ​Auto-Save Validation​
Close the page directly to auto-save changes (no need to click "Save").
3️⃣ ​Post-Restart Verification​
Restart VS Code and verify the environment list ​reflects recent updates.

Should you continue experiencing issues, please contact our support team at ​support@echoapi.com.
Thank you for your understanding and continued trust in our solutions! 😊

Warm regards,
The EchoAPI Team

**Comment by servo98** [comment]
Hello, Im also trying to save an environment but no save button as doc say [here](https://www.echoapi.com/wiki/docs/http/environment-variables)
Not even closing and restarting works

**Comment by bzw1204** [comment]
It has been updated to the latest version, but it still doesn't work. After the input box loses focus, it prompts that the operation is successful, but the content is not actually saved.

**Comment by WahomeMark** [comment]
Facing the same issue in ​version 1.7.3

**Comment by lara-joyet** [comment]
Hey everyone,

We want to update you that the issue regarding saving environment information on Windows systems has been resolved in version 1.7.4 ✅

To verify the fix, please follow these steps:

1️⃣ Setting Up the Environment
Go to the Environment section and ensure all required fields are filled out correctly.

2️⃣ Save the Environment Settings Manually
In the bottom-right corner of the interface, you'll find a Save button. Click it to save your environment settings. Don’t skip this step, as changes won’t be saved otherwise!

3️⃣ Verifying After a Restart
After saving, please restart VS Code to ensure the settings take effect. Once it restarts, check the environment list—you should see the recent updates there.

If you have any further issues after following these steps, please feel free to reach out to our support team at **support@echoapi.com**. We're here to help!

Thank you for your patience and continued support! 😊

Best regards,

The EchoAPI Team

**Comment by RexFinn** [comment]
Hey everyone,

We want to update you that the issue regarding saving environment information on Windows systems has been resolved in version 1.7.4 ✅

To verify the fix, please follow these steps:

1️⃣ Setting Up the Environment
Go to the Environment section and ensure all required fields are filled out correctly.

2️⃣ Save the Environment Settings Manually
In the bottom-right corner of the interface, you'll find a Save button. Click it to save your environment settings. Don’t skip this step, as changes won’t be saved otherwise!

3️⃣ Verifying After a Restart
After saving, please restart VS Code to ensure the settings take effect. Once it restarts, check the environment list—you should see the recent updates there.

If you have any further issues after following these steps, please feel free to reach out to our support team at **support@echoapi.com**. We're here to help!

Thank you for your patience and continued support! 😊

Best regards,

The EchoAPI Team

**Comment by WahomeMark** [comment]
Works well in version 1.7.4. Thank you!

**Comment by Corys9** [comment]
Updating to 1.7.4 and restarting the extension added the 'Save' button, which fixes the issue.
Thank you
