### ISSUE TITLE
The url.host / url.path are modified after export postman collection file → broken request URLs (404 Not Found).

### ISSUE THREAD

**Issue by levanleuitvn** [EchoAPI-Team/echoapi-for-vscode-support#40]
**Description**:
When exporting a Postman collection from EchoAPI, the **url.path** and **url.host** fields are modified incorrectly.
- **url.path**: **removed**
- **url.host**: **changed** 

Since Postman/Newman relies on the combination of `host + path + query` to generate the final request URL, this results in malformed URLs and execution errors **(404 Not Found)**.

**Case 1: Request without explicit protocol (http/https)**
The request request.url.host in the exported Postman collection contains the full path information (same as the raw information)
**Example:** GET `{{env_host}}/path_param?query_key=query_value`

- Original Postman collection JSON:
```json
"url": {
  "raw": "{{env_host}}/path_param?query_key=query_value",
  "host": [
    "{{env_host}}"
  ],
  "path": [
    "path_param"
  ],
  "query": [
    { "key": "query_key", "value": "query_value" }
  ]
}
```

- After import into EchoAPI and export to postman collection:
```json
"url": {
  "raw": "http://{{env_host}}/path_param?query_key=query_value",
  "query": [
    {
      "key": "query_key",
      "value": "query_value",
      "description": "",
      "disabled": false
    }
  ],
  "variable": [],
  "host": [
    "{{env_host}}/path_param?query_key=query_value"
  ]
}
```

- **Issue**:
    + host contains the full path + query string
    + When display  in Postman, the URL becomes: 
       `{{env_host}}/path_param?query_key=query_value?query_key=query_value`
        → Duplicate query parameter (NG).

**Case 2: Request with explicit protocol (http/https)**
**Example:** GET `http://{{env_host}}/path_param?query_key=query_value`

- Original Postman collection JSON:
```json
"url": {
  "raw": "http://{{env_host}}/path_param?query_key=query_value",
  "protocol": "http",
  "host": [
    "{{env_host}}"
  ],
  "path": [
    "path_param"
  ],
  "query": [
    { "key": "query_key", "value": "query_value" }
  ]
}
```

- After import into EchoAPI and export to postman collection:
```json
"url": {
  "raw": "http://{{env_host}}/path_param?query_key=query_value",
  "query": [
    {
      "key": "query_key",
      "value": "query_value",
      "description": "",
      "disabled": false
    }
  ],
  "variable": [],
  "host": [
    "{{env_host}}"
  ]
}

```

- **Issue**:
    + `path` is missing.
    + When display in Postman, the URL becomes: 
       `http://{{env_host}}?query_key=query_value`
        → missing path parameter (NG).

**Comment by xbw19975** [comment]
I also encountered the same situation, but I didn't find this problem in the latest version of the EchoAPI client. I hope the VSCode plugin can also solve this issue as soon as possible.

**Comment by RexFinn** [comment]
Hi there! Good news - the issue you reported has been fixed in the latest version (V1.7.13). Please update your app.

**Comment by quannguyen-tma** [comment]
Hi there (@RexFinn ),

Thanks for the update! I’ve updated to the latest version (V1.7.13) and also tried removing and reinstalling the VS Code extension, but the issue still seems to persist on my side.

Could you please double-check or share more details about the fix implementation?
Here are some details from my latest test.
Collection:  

[Local Project_echoapi_postman.json](https://github.com/user-attachments/files/23083778/Local.Project_echoapi_postman.json)

### Echo API

Verion: 1.7.13

<img width="343" height="315" alt="Image" src="https://github.com/user-attachments/assets/447ccebf-b6f9-479b-91d5-52aaf0bfaaee" />



<img width="745" height="224" alt="Image" src="https://github.com/user-attachments/assets/5caa49b4-9e03-4b55-b3fa-6cd575218ac0" />

<img width="826" height="242" alt="Image" src="https://github.com/user-attachments/assets/bb114224-dd7a-4784-ae67-13fa777120a9" />

### Import to Postman

<img width="1045" height="279" alt="Image" src="https://github.com/user-attachments/assets/330165d1-2c90-418f-b6d2-2e56ac6d4c4e" />

<img width="1034" height="293" alt="Image" src="https://github.com/user-attachments/assets/a290ac6b-577c-4f9a-a569-c2e738ef14e4" />
